# Generated by Django 3.0.2 on 2020-01-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pseudo',
        ),
    ]
