# Generated by Django 3.0.2 on 2020-01-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_pseudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pseudo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
